### ISSUE TITLE
Escaping multiple dollar signs

### ISSUE THREAD

**Issue by mgiamberardino** [thesimj/envyaml#31]
We are using this package for managing environment yaml files and we are facing a scenario where we need to have multiple dollar signs and all of them should be escaped:

```yaml
user_one:
  username: some_user
  password: SomePa$$$word
```

Currently, the package is failing to parse this yaml since `$word` does not exist in the environment. After reading about escaping and testing the following values escaping each dollar sign:
```yaml
user_one:
  username: some_user
  password: SomePa$$$$$$word
```
Now the password is having `SomePa$word` as a value.

After digging a bit into the code this seems to be an issue related to how content is getting replaced for escaped dollar signs.

I'll raise a PR with a solution proposal and refer to this issue.
